import '../../styles.css';
import ColorPicker from '../../components/ColorPicker.vue';
debugger; /* PartiallyEnd: #3632/scriptSetup.vue */
const __VLS_ctx = {};
let __VLS_components;
let __VLS_directives;
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex flex-1 mt-[60px] ml-21 px-6 py-12 lg:px-8 bg-blue-50 dark:bg-zinc-950" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.form, __VLS_intrinsicElements.form)(Object.assign({ class: "flex" }, { action: "" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex flex-col w-110 h-full" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex flex-col p-5 justify-evenly rounded-3xl ml-10 my-6 h-1/3 shadow-[0px_5px_3px_4px_rgba(0,_0,_100,_0.2)] transition-all duration-300 ease-in-out hover:mb-10 hover:mt-2 hover:shadow-[0px_21px_3px_4px_rgba(0,_0,_100,_0.2)] dark:shadow-[0px_5px_3px_4px_rgba(200,_200,_250,_0.15)] dark:hover:shadow-[0px_21px_3px_4px_rgba(200,_200,_250,_0.15)]" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.label, __VLS_intrinsicElements.label)(Object.assign({ for: "excel" }, { class: "font-bold text-slate-800 dark:text-slate-300" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.input, __VLS_intrinsicElements.input)(Object.assign({ type: "file", id: "excel", name: "excel" }, { class: "file:bg-slate-300 file:p-1 file:cursor-pointer text-sm text-gray-900 cursor-pointer bg-white border-solid border-2 border-slate-300 rounded-md dark:bg-slate-700 dark:text-slate-400 dark:file:bg-slate-900 dark:border-slate-900" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.label, __VLS_intrinsicElements.label)(Object.assign({ for: "template" }, { class: "font-bold text-slate-800 dark:text-slate-300" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.select, __VLS_intrinsicElements.select)(Object.assign({ name: "template", id: "template" }, { class: "border-slate-400 border-2 rounded-md p-1 dark:border-slate-800 dark:text-slate-500" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({
    value: "1",
});
__VLS_asFunctionalElement(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({
    value: "2",
});
__VLS_asFunctionalElement(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({
    value: "3",
});
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex flex-col p-5 justify-evenly rounded-3xl ml-10 my-6 h-1/3 shadow-[0px_5px_3px_4px_rgba(0,_0,_100,_0.2)] transition-all duration-300 ease-in-out hover:mb-10 hover:mt-2 hover:shadow-[0px_21px_3px_4px_rgba(0,_0,_100,_0.2)] dark:shadow-[0px_5px_3px_4px_rgba(200,_200,_250,_0.15)] dark:hover:shadow-[0px_21px_3px_4px_rgba(200,_200,_250,_0.15)]" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.label, __VLS_intrinsicElements.label)(Object.assign({ for: "logo" }, { class: "font-bold text-slate-800 dark:text-slate-300" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.input, __VLS_intrinsicElements.input)(Object.assign({ type: "file", id: "excel", name: "excel" }, { class: "file:bg-slate-300 file:p-1 file:cursor-pointer text-sm text-gray-900 cursor-pointer bg-white border-solid border-2 border-slate-300 rounded-md dark:bg-slate-700 dark:text-slate-400 dark:file:bg-slate-900 dark:border-slate-900" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.label, __VLS_intrinsicElements.label)(Object.assign({ for: "image" }, { class: "font-bold text-slate-800 dark:text-slate-300" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.input, __VLS_intrinsicElements.input)(Object.assign({ type: "file", id: "excel", name: "excel" }, { class: "file:bg-slate-300 file:p-1 file:cursor-pointer text-sm text-gray-900 cursor-pointer bg-white border-solid border-2 border-slate-300 rounded-md dark:bg-slate-700 dark:text-slate-400 dark:file:bg-slate-900 dark:border-slate-900" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex p-5 justify-evenly rounded-3xl ml-10 my-6 h-1/3 shadow-[0px_5px_3px_4px_rgba(0,_0,_100,_0.2)] transition-all duration-300 ease-in-out hover:mb-10 hover:mt-2 hover:shadow-[0px_21px_3px_4px_rgba(0,_0,_100,_0.2)] dark:shadow-[0px_5px_3px_4px_rgba(200,_200,_250,_0.15)] dark:hover:shadow-[0px_21px_3px_4px_rgba(200,_200,_250,_0.15)]" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex flex-col m-auto" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.label, __VLS_intrinsicElements.label)(Object.assign({ for: "primarycol" }, { class: "font-bold text-slate-800 dark:text-slate-300" }));
/** @type {[typeof ColorPicker, ]} */ ;
// @ts-ignore
const __VLS_0 = __VLS_asFunctionalComponent(ColorPicker, new ColorPicker({}));
const __VLS_1 = __VLS_0({}, ...__VLS_functionalComponentArgsRest(__VLS_0));
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex flex-col m-auto" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.label, __VLS_intrinsicElements.label)(Object.assign({ for: "primarycol" }, { class: "font-bold text-slate-800 dark:text-slate-300" }));
/** @type {[typeof ColorPicker, ]} */ ;
// @ts-ignore
const __VLS_3 = __VLS_asFunctionalComponent(ColorPicker, new ColorPicker({}));
const __VLS_4 = __VLS_3({}, ...__VLS_functionalComponentArgsRest(__VLS_3));
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex w-150 h-full" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "rounded-2xl my-6 mx-10 w-full shadow-[0px_5px_3px_4px_rgba(0,_0,_100,_0.2)] transition-all duration-300 ease-in-out hover:mb-10 hover:mt-2 hover:shadow-[0px_21px_3px_4px_rgba(0,_0,_100,_0.2)] dark:shadow-[0px_5px_3px_4px_rgba(200,_200,_250,_0.15)] dark:hover:shadow-[0px_21px_3px_4px_rgba(200,_200,_250,_0.15)]" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)(Object.assign({ class: "text-2xl" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex flex-1 h-full" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)(Object.assign({ class: "flex items-center flex-1 justify-center rounded-2xl my-6 mr-10 w-full bg-white border-slate-300 dark:bg-zinc-900 dark:border-slate-800 border-3" }));
__VLS_asFunctionalElement(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)(Object.assign({ class: "text-2xl" }));
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['flex-1']} */ ;
/** @type {__VLS_StyleScopedClasses['mt-[60px]']} */ ;
/** @type {__VLS_StyleScopedClasses['ml-21']} */ ;
/** @type {__VLS_StyleScopedClasses['px-6']} */ ;
/** @type {__VLS_StyleScopedClasses['py-12']} */ ;
/** @type {__VLS_StyleScopedClasses['lg:px-8']} */ ;
/** @type {__VLS_StyleScopedClasses['bg-blue-50']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:bg-zinc-950']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['flex-col']} */ ;
/** @type {__VLS_StyleScopedClasses['w-110']} */ ;
/** @type {__VLS_StyleScopedClasses['h-full']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['flex-col']} */ ;
/** @type {__VLS_StyleScopedClasses['p-5']} */ ;
/** @type {__VLS_StyleScopedClasses['justify-evenly']} */ ;
/** @type {__VLS_StyleScopedClasses['rounded-3xl']} */ ;
/** @type {__VLS_StyleScopedClasses['ml-10']} */ ;
/** @type {__VLS_StyleScopedClasses['my-6']} */ ;
/** @type {__VLS_StyleScopedClasses['h-1/3']} */ ;
/** @type {__VLS_StyleScopedClasses['shadow-[0px_5px_3px_4px_rgba(0,_0,_100,_0.2)]']} */ ;
/** @type {__VLS_StyleScopedClasses['transition-all']} */ ;
/** @type {__VLS_StyleScopedClasses['duration-300']} */ ;
/** @type {__VLS_StyleScopedClasses['ease-in-out']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:mb-10']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:mt-2']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:shadow-[0px_21px_3px_4px_rgba(0,_0,_100,_0.2)]']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:shadow-[0px_5px_3px_4px_rgba(200,_200,_250,_0.15)]']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:hover:shadow-[0px_21px_3px_4px_rgba(200,_200,_250,_0.15)]']} */ ;
/** @type {__VLS_StyleScopedClasses['font-bold']} */ ;
/** @type {__VLS_StyleScopedClasses['text-slate-800']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['file:bg-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['file:p-1']} */ ;
/** @type {__VLS_StyleScopedClasses['file:cursor-pointer']} */ ;
/** @type {__VLS_StyleScopedClasses['text-sm']} */ ;
/** @type {__VLS_StyleScopedClasses['text-gray-900']} */ ;
/** @type {__VLS_StyleScopedClasses['cursor-pointer']} */ ;
/** @type {__VLS_StyleScopedClasses['bg-white']} */ ;
/** @type {__VLS_StyleScopedClasses['border-solid']} */ ;
/** @type {__VLS_StyleScopedClasses['border-2']} */ ;
/** @type {__VLS_StyleScopedClasses['border-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['rounded-md']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:bg-slate-700']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-400']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:file:bg-slate-900']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:border-slate-900']} */ ;
/** @type {__VLS_StyleScopedClasses['font-bold']} */ ;
/** @type {__VLS_StyleScopedClasses['text-slate-800']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['border-slate-400']} */ ;
/** @type {__VLS_StyleScopedClasses['border-2']} */ ;
/** @type {__VLS_StyleScopedClasses['rounded-md']} */ ;
/** @type {__VLS_StyleScopedClasses['p-1']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:border-slate-800']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-500']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['flex-col']} */ ;
/** @type {__VLS_StyleScopedClasses['p-5']} */ ;
/** @type {__VLS_StyleScopedClasses['justify-evenly']} */ ;
/** @type {__VLS_StyleScopedClasses['rounded-3xl']} */ ;
/** @type {__VLS_StyleScopedClasses['ml-10']} */ ;
/** @type {__VLS_StyleScopedClasses['my-6']} */ ;
/** @type {__VLS_StyleScopedClasses['h-1/3']} */ ;
/** @type {__VLS_StyleScopedClasses['shadow-[0px_5px_3px_4px_rgba(0,_0,_100,_0.2)]']} */ ;
/** @type {__VLS_StyleScopedClasses['transition-all']} */ ;
/** @type {__VLS_StyleScopedClasses['duration-300']} */ ;
/** @type {__VLS_StyleScopedClasses['ease-in-out']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:mb-10']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:mt-2']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:shadow-[0px_21px_3px_4px_rgba(0,_0,_100,_0.2)]']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:shadow-[0px_5px_3px_4px_rgba(200,_200,_250,_0.15)]']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:hover:shadow-[0px_21px_3px_4px_rgba(200,_200,_250,_0.15)]']} */ ;
/** @type {__VLS_StyleScopedClasses['font-bold']} */ ;
/** @type {__VLS_StyleScopedClasses['text-slate-800']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['file:bg-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['file:p-1']} */ ;
/** @type {__VLS_StyleScopedClasses['file:cursor-pointer']} */ ;
/** @type {__VLS_StyleScopedClasses['text-sm']} */ ;
/** @type {__VLS_StyleScopedClasses['text-gray-900']} */ ;
/** @type {__VLS_StyleScopedClasses['cursor-pointer']} */ ;
/** @type {__VLS_StyleScopedClasses['bg-white']} */ ;
/** @type {__VLS_StyleScopedClasses['border-solid']} */ ;
/** @type {__VLS_StyleScopedClasses['border-2']} */ ;
/** @type {__VLS_StyleScopedClasses['border-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['rounded-md']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:bg-slate-700']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-400']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:file:bg-slate-900']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:border-slate-900']} */ ;
/** @type {__VLS_StyleScopedClasses['font-bold']} */ ;
/** @type {__VLS_StyleScopedClasses['text-slate-800']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['file:bg-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['file:p-1']} */ ;
/** @type {__VLS_StyleScopedClasses['file:cursor-pointer']} */ ;
/** @type {__VLS_StyleScopedClasses['text-sm']} */ ;
/** @type {__VLS_StyleScopedClasses['text-gray-900']} */ ;
/** @type {__VLS_StyleScopedClasses['cursor-pointer']} */ ;
/** @type {__VLS_StyleScopedClasses['bg-white']} */ ;
/** @type {__VLS_StyleScopedClasses['border-solid']} */ ;
/** @type {__VLS_StyleScopedClasses['border-2']} */ ;
/** @type {__VLS_StyleScopedClasses['border-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['rounded-md']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:bg-slate-700']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-400']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:file:bg-slate-900']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:border-slate-900']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['p-5']} */ ;
/** @type {__VLS_StyleScopedClasses['justify-evenly']} */ ;
/** @type {__VLS_StyleScopedClasses['rounded-3xl']} */ ;
/** @type {__VLS_StyleScopedClasses['ml-10']} */ ;
/** @type {__VLS_StyleScopedClasses['my-6']} */ ;
/** @type {__VLS_StyleScopedClasses['h-1/3']} */ ;
/** @type {__VLS_StyleScopedClasses['shadow-[0px_5px_3px_4px_rgba(0,_0,_100,_0.2)]']} */ ;
/** @type {__VLS_StyleScopedClasses['transition-all']} */ ;
/** @type {__VLS_StyleScopedClasses['duration-300']} */ ;
/** @type {__VLS_StyleScopedClasses['ease-in-out']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:mb-10']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:mt-2']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:shadow-[0px_21px_3px_4px_rgba(0,_0,_100,_0.2)]']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:shadow-[0px_5px_3px_4px_rgba(200,_200,_250,_0.15)]']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:hover:shadow-[0px_21px_3px_4px_rgba(200,_200,_250,_0.15)]']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['flex-col']} */ ;
/** @type {__VLS_StyleScopedClasses['m-auto']} */ ;
/** @type {__VLS_StyleScopedClasses['font-bold']} */ ;
/** @type {__VLS_StyleScopedClasses['text-slate-800']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['flex-col']} */ ;
/** @type {__VLS_StyleScopedClasses['m-auto']} */ ;
/** @type {__VLS_StyleScopedClasses['font-bold']} */ ;
/** @type {__VLS_StyleScopedClasses['text-slate-800']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:text-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['w-150']} */ ;
/** @type {__VLS_StyleScopedClasses['h-full']} */ ;
/** @type {__VLS_StyleScopedClasses['rounded-2xl']} */ ;
/** @type {__VLS_StyleScopedClasses['my-6']} */ ;
/** @type {__VLS_StyleScopedClasses['mx-10']} */ ;
/** @type {__VLS_StyleScopedClasses['w-full']} */ ;
/** @type {__VLS_StyleScopedClasses['shadow-[0px_5px_3px_4px_rgba(0,_0,_100,_0.2)]']} */ ;
/** @type {__VLS_StyleScopedClasses['transition-all']} */ ;
/** @type {__VLS_StyleScopedClasses['duration-300']} */ ;
/** @type {__VLS_StyleScopedClasses['ease-in-out']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:mb-10']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:mt-2']} */ ;
/** @type {__VLS_StyleScopedClasses['hover:shadow-[0px_21px_3px_4px_rgba(0,_0,_100,_0.2)]']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:shadow-[0px_5px_3px_4px_rgba(200,_200,_250,_0.15)]']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:hover:shadow-[0px_21px_3px_4px_rgba(200,_200,_250,_0.15)]']} */ ;
/** @type {__VLS_StyleScopedClasses['text-2xl']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['flex-1']} */ ;
/** @type {__VLS_StyleScopedClasses['h-full']} */ ;
/** @type {__VLS_StyleScopedClasses['flex']} */ ;
/** @type {__VLS_StyleScopedClasses['items-center']} */ ;
/** @type {__VLS_StyleScopedClasses['flex-1']} */ ;
/** @type {__VLS_StyleScopedClasses['justify-center']} */ ;
/** @type {__VLS_StyleScopedClasses['rounded-2xl']} */ ;
/** @type {__VLS_StyleScopedClasses['my-6']} */ ;
/** @type {__VLS_StyleScopedClasses['mr-10']} */ ;
/** @type {__VLS_StyleScopedClasses['w-full']} */ ;
/** @type {__VLS_StyleScopedClasses['bg-white']} */ ;
/** @type {__VLS_StyleScopedClasses['border-slate-300']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:bg-zinc-900']} */ ;
/** @type {__VLS_StyleScopedClasses['dark:border-slate-800']} */ ;
/** @type {__VLS_StyleScopedClasses['border-3']} */ ;
/** @type {__VLS_StyleScopedClasses['text-2xl']} */ ;
var __VLS_dollars;
const __VLS_self = (await import('vue')).defineComponent({
    setup() {
        return {
            ColorPicker: ColorPicker,
        };
    },
});
export default (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
; /* PartiallyEnd: #4569/main.vue */
